### ISSUE TITLE
InterpLUT example doesn't mention it has to be in a method

### ISSUE THREAD

**Issue by shaunsingh** [FTCLib/FTCLib-Docs#7]
In the utility functions docs: https://docs.ftclib.org/ftclib/features/util

the interpLUT example doesn't mention it has to be in a method 

![image](https://user-images.githubusercontent.com/71196912/99918094-ab1d7e80-2ce2-11eb-876c-61fb0c233083.png)

when it should be more like this

![image](https://user-images.githubusercontent.com/71196912/99918103-bc668b00-2ce2-11eb-9e8e-b09ba7954194.png)

(with brackets)

**Comment by JIceberg** [comment]
This is a general Java programming convention. You cannot have statements outside of a method body. The docs are meant to represent the usage rather than create an entire table. The utilization of the double brackets `{{ }}` is also a Java convention to call methods within an instantiation.

**Comment by shaunsingh** [comment]
I see. I thought it was just a bit confusing since the previous example had them but this didn't?

**Comment by JIceberg** [comment]
> I see. I thought it was just a bit confusing since the previous example had them but this didn't?

That's because LUT is a map so it makes more sense for the method call in instantiation; but it is true that you can do it with both.

**Comment by shaunsingh** [comment]
I see. Thank You!
