### ISSUE TITLE
consider providing additional explanation in the section on custom triggers

### ISSUE THREAD

**Issue by mgfrog** [FTCLib/FTCLib-Docs#9]
https://github.com/FTCLib/FTCLib-Docs/blob/v1.2.0/command-base/command-system/binding-commands-to-triggers.md

the section on custom triggers could benefit from an explanation or example of when/why you would want to create a custom trigger.  like would this be used with sensors?  as an example, if you had a limit switch would you make a custom trigger for the state of the sensor and then bind it to a command to stop an arm/lift motor, or would this be overkill?  Other examples would be detecting a particular color with a color sensor, or a distance with a distance sensor.  It just isn't clear if this is a good use for commands.  the last sentence "Note: This is not very effective, but can be done if you want to write your own custom methods (A.K.A. being a try-hard)" makes it seem like this type of usage would not be a good idea.  So stated more generally, should custom triggers be used with sensors?  If not, where do sensors fit in with command based robot control?

**Comment by JIceberg** [comment]
All good points! With command based, there are two ways that I can see a binding being made:
1. The binding is produced by some sort of "triggering input," which can be constructed using a custom trigger
2. A conditional command that monitors the state of the sensor and when a condition is met, different commands are run

I think these are good points to bring up in the documentation and will update it accordingly. I appreciate the feedback.
